In [81]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show ,output_file
from bokeh.embed import components
from bokeh.resources import CDN

In [68]:
start=datetime.datetime(2016,3,1)
end=datetime.datetime(2016,5,10)
df=data.DataReader(name='GOOG',data_source="google",start=start,end=end)
df

              Open    High     Low   Close   Volume
Date
2016-03-01  703.62  718.81  699.77  718.81  2147442
2016-03-02  719.00  720.00  712.00  718.85  1627753
2016-03-03  718.68  719.45  706.02  712.42  1956761
2016-03-04  714.99  716.49  706.02  710.89  1967873
2016-03-07  706.90  708.09  686.90  695.16  2985094
2016-03-08  688.59  703.79  685.34  693.97  2063357
2016-03-09  698.47  705.68  694.00  705.24  1418704
2016-03-10  708.12  716.44  703.36  712.82  2829412
2016-03-11  720.00  726.92  717.12  726.82  1963907
2016-03-14  726.81  735.50  725.15  730.49  1716910
2016-03-15  726.92  732.29  724.77  728.33  1720965
2016-03-16  726.37  737.47  724.51  736.09  1572329
2016-03-17  736.45  743.07  736.00  737.78  1856800
2016-03-18  741.86  742.00  731.83  737.60  2796376
2016-03-21  736.50  742.50  733.52  742.09  1831839
2016-03-22  737.46  745.00  737.46  740.75  1264396
2016-03-23  742.36  745.72  736.15  738.06  1421861
2016-03-24  732.01  737.75  731.00  735.30  1564782
2016-03-28  736.79  738.99  732.50  733.53  1299812
2016-03-29  734.59  747.25  728.76  744.77  1902128
2016-03-30  750.10  757.88  748.74  750.53  1780998
2016-03-31  749.25  750.85  740.94  744.95  1712375
2016-04-01  738.60  750.34  737.00  749.91  1574870
2016-04-04  750.06  752.80  742.43  745.29  1131843
2016-04-05  738.00  742.80  735.37  737.80  1129829
2016-04-06  735.77  746.24  735.56  745.69  1050193
2016-04-07  745.37  747.00  736.28  740.28  1429504
2016-04-08  743.97  745.45  735.55  739.15  1285755
2016-04-11  743.02  745.00  736.05  736.10  1211762
2016-04-12  738.00  743.83  731.01  743.09  1349734
2016-04-13  749.16  754.38  744.26  751.72  1707095
2016-04-14  754.01  757.31  752.70  753.20  1130971
2016-04-15  753.98  761.00  752.69  759.00  1800413
2016-04-18  760.46  768.05  757.30  766.61  1555953
2016-04-19  769.51  769.90  749.33  753.93  2027642
2016-04-20  758.00  758.13  750.01  752.67  1525591
2016-04-21  755.38  760.45  749.55  759.14  2743620
2016-04-22  726.30  736.12  713.61  718.77  5939199
2016-04-25  716.10  723.93  715.59  723.15  1955567
2016-04-26  725.42  725.77  703.03  708.14  2727185
2016-04-27  707.29  708.98  692.37  705.84  3086722
2016-04-28  708.26  714.17  689.55  691.02  2851108
2016-04-29  690.70  697.62  689.00  693.01  2484273
2016-05-02  697.63  700.64  691.00  698.21  1644126
2016-05-03  696.87  697.84  692.00  692.36  1530993
2016-05-04  690.49  699.75  689.01  695.70  1688569
2016-05-05  697.70  702.32  695.72  701.43  1677405
2016-05-06  698.38  711.86  698.11  711.12  1826146
2016-05-09  712.00  718.71  710.00  712.90  1508423
2016-05-10  716.75  723.50  715.72  723.18  1563105

In [70]:
def inc_dec(c,o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"]=[inc_dec(c,o) for c, o in zip(df.Close,df.Open)]
df["Middle"]=(df.Open-df.Close)/2
df["Height"]=abs(df.Close-df.Open)
df

              Open    High     Low   Close   Volume    Status  Middle  Height
Date
2016-03-01  703.62  718.81  699.77  718.81  2147442  Increase  -7.595   15.19
2016-03-02  719.00  720.00  712.00  718.85  1627753  Decrease   0.075    0.15
2016-03-03  718.68  719.45  706.02  712.42  1956761  Decrease   3.130    6.26
2016-03-04  714.99  716.49  706.02  710.89  1967873  Decrease   2.050    4.10
2016-03-07  706.90  708.09  686.90  695.16  2985094  Decrease   5.870   11.74
2016-03-08  688.59  703.79  685.34  693.97  2063357  Increase  -2.690    5.38
2016-03-09  698.47  705.68  694.00  705.24  1418704  Increase  -3.385    6.77
2016-03-10  708.12  716.44  703.36  712.82  2829412  Increase  -2.350    4.70
2016-03-11  720.00  726.92  717.12  726.82  1963907  Increase  -3.410    6.82
2016-03-14  726.81  735.50  725.15  730.49  1716910  Increase  -1.840    3.68
2016-03-15  726.92  732.29  724.77  728.33  1720965  Increase  -0.705    1.41
2016-03-16  726.37  737.47  724.51  736.09  1572329  Increase  -4.860    9.72
2016-03-17  736.45  743.07  736.00  737.78  1856800  Increase  -0.665    1.33
2016-03-18  741.86  742.00  731.83  737.60  2796376  Decrease   2.130    4.26
2016-03-21  736.50  742.50  733.52  742.09  1831839  Increase  -2.795    5.59
2016-03-22  737.46  745.00  737.46  740.75  1264396  Increase  -1.645    3.29
2016-03-23  742.36  745.72  736.15  738.06  1421861  Decrease   2.150    4.30
2016-03-24  732.01  737.75  731.00  735.30  1564782  Increase  -1.645    3.29
2016-03-28  736.79  738.99  732.50  733.53  1299812  Decrease   1.630    3.26
2016-03-29  734.59  747.25  728.76  744.77  1902128  Increase  -5.090   10.18
2016-03-30  750.10  757.88  748.74  750.53  1780998  Increase  -0.215    0.43
2016-03-31  749.25  750.85  740.94  744.95  1712375  Decrease   2.150    4.30
2016-04-01  738.60  750.34  737.00  749.91  1574870  Increase  -5.655   11.31
2016-04-04  750.06  752.80  742.43  745.29  1131843  Decrease   2.385    4.77
2016-04-05  738.00  742.80  735.37  737.80  1129829  Decrease   0.100    0.20
2016-04-06  735.77  746.24  735.56  745.69  1050193  Increase  -4.960    9.92
2016-04-07  745.37  747.00  736.28  740.28  1429504  Decrease   2.545    5.09
2016-04-08  743.97  745.45  735.55  739.15  1285755  Decrease   2.410    4.82
2016-04-11  743.02  745.00  736.05  736.10  1211762  Decrease   3.460    6.92
2016-04-12  738.00  743.83  731.01  743.09  1349734  Increase  -2.545    5.09
2016-04-13  749.16  754.38  744.26  751.72  1707095  Increase  -1.280    2.56
2016-04-14  754.01  757.31  752.70  753.20  1130971  Decrease   0.405    0.81
2016-04-15  753.98  761.00  752.69  759.00  1800413  Increase  -2.510    5.02
2016-04-18  760.46  768.05  757.30  766.61  1555953  Increase  -3.075    6.15
2016-04-19  769.51  769.90  749.33  753.93  2027642  Decrease   7.790   15.58
2016-04-20  758.00  758.13  750.01  752.67  1525591  Decrease   2.665    5.33
2016-04-21  755.38  760.45  749.55  759.14  2743620  Increase  -1.880    3.76
2016-04-22  726.30  736.12  713.61  718.77  5939199  Decrease   3.765    7.53
2016-04-25  716.10  723.93  715.59  723.15  1955567  Increase  -3.525    7.05
2016-04-26  725.42  725.77  703.03  708.14  2727185  Decrease   8.640   17.28
2016-04-27  707.29  708.98  692.37  705.84  3086722  Decrease   0.725    1.45
2016-04-28  708.26  714.17  689.55  691.02  2851108  Decrease   8.620   17.24
2016-04-29  690.70  697.62  689.00  693.01  2484273  Increase  -1.155    2.31
2016-05-02  697.63  700.64  691.00  698.21  1644126  Increase  -0.290    0.58
2016-05-03  696.87  697.84  692.00  692.36  1530993  Decrease   2.255    4.51
2016-05-04  690.49  699.75  689.01  695.70  1688569  Increase  -2.605    5.21
2016-05-05  697.70  702.32  695.72  701.43  1677405  Increase  -1.865    3.73
2016-05-06  698.38  711.86  698.11  711.12  1826146  Increase  -6.370   12.74
2016-05-09  712.00  718.71  710.00  712.90  1508423  Increase  -0.450    0.90
2016-05-10  716.75  723.50  715.72  723.18  1563105  Increase  -3.215    6.43

In [82]:
p=figure(x_axis_type='datetime', width=1000,height=300,responsive=True)
p.title.text="Candlestick Chart"
p.grid.grid_line_alpha=0.4

hours_12=12*60*60*1000
p.segment(df.index,df.High,df.index, df.Low, color="Black")

date_increase = df.index[df.Close > df.Open]
date_decrease = df.index[df.Close < df.Open]
p.rect(df.index[df.Status=="Increase"],(df.Open+df.Close)/2,hours_12,abs(df.Open-df.Close),fill_color="green",line_color="black")
p.rect(df.index[df.Status=="Decrease"],(df.Open+df.Close)/2,hours_12,abs(df.Open-df.Close),fill_color="red",line_color="black")

#output_file("cs.html")#show(p)

type(components(p))

script1, div1 = components(p)

cdn_js = CDN.js_files
cdn_css=CDN.css_files
print(div1)

<div class="bk-root">
    <div class="plotdiv" id="ff9ef537-f3cb-479d-ac45-599626ca2a4f"></div>
</div>

In [88]:
cdn_js

['https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js']

In [87]:
cdn_css

['https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.css',
 'https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.css']